hyperparameters:
  model_type: ['DistillBertEmotion']
  optimizer_type: ['adam']
  loss_criterion: ['crossentropy']
  lr: [0.00002]
  epochs: [30]
  batch_size: [64]
  patience_es: [8]
  use_scheduler: [True]
  patience_lr: [5]
  save_condition: ['loss']