hyperparameters:
  model_type: ['PyramidCNN']
  optimizer_type: ['adam']
  loss_criterion: ['bcelosswithlogits']
  lr: [0.001]
  epochs: [100]
  batch_size: [64]
  patience_es: [5]
  scheduler_type: ['']
  patience_lr: [3]
  save_condition: ['acc']
  fix_length: [null]
  context_size: [0]
  pyramid: [[256,256]]
  fcs: [[128]]
  batch_norm: [0]
  alpha: [0.2]
