hyperparameters:
  model_type: ['DistillBert']
  optimizer_type: ['adam']
  loss_criterion: ['crossentropy']
  lr: [0.00002]
  epochs: [300]
  batch_size: [16]
  patience_es: [5]
  scheduler_type: ['linear_schedule_with_warmup']
  patience_lr: [3]
  save_condition: ['acc']
  fix_length: [null]